export const REGION_OPTIONS = [
  { province: "暂不填写", cities: ["暂不填写"] },
  { province: "北京", cities: ["北京"] },
  { province: "上海", cities: ["上海"] },
  { province: "天津", cities: ["天津"] },
  { province: "重庆", cities: ["重庆", "万州", "涪陵"] },
  { province: "河北", cities: ["石家庄", "唐山", "秦皇岛", "保定", "廊坊", "邯郸"] },
  { province: "山西", cities: ["太原", "大同", "长治", "运城", "临汾"] },
  { province: "内蒙古", cities: ["呼和浩特", "包头", "赤峰", "鄂尔多斯", "呼伦贝尔"] },
  { province: "辽宁", cities: ["沈阳", "大连", "鞍山", "锦州", "丹东"] },
  { province: "吉林", cities: ["长春", "吉林", "四平", "延边", "通化"] },
  { province: "黑龙江", cities: ["哈尔滨", "齐齐哈尔", "牡丹江", "佳木斯", "大庆"] },
  { province: "江苏", cities: ["南京", "苏州", "无锡", "常州", "南通", "徐州"] },
  { province: "浙江", cities: ["杭州", "宁波", "温州", "绍兴", "金华", "台州"] },
  { province: "安徽", cities: ["合肥", "芜湖", "蚌埠", "阜阳", "安庆"] },
  { province: "福建", cities: ["福州", "厦门", "泉州", "漳州", "莆田"] },
  { province: "江西", cities: ["南昌", "赣州", "九江", "上饶", "宜春"] },
  { province: "山东", cities: ["济南", "青岛", "烟台", "潍坊", "临沂", "济宁"] },
  { province: "河南", cities: ["郑州", "洛阳", "开封", "南阳", "新乡", "信阳"] },
  { province: "湖北", cities: ["武汉", "宜昌", "襄阳", "荆州", "黄冈"] },
  { province: "湖南", cities: ["长沙", "株洲", "湘潭", "衡阳", "岳阳", "郴州"] },
  { province: "广东", cities: ["广州", "深圳", "佛山", "东莞", "珠海", "中山"] },
  { province: "广西", cities: ["南宁", "桂林", "柳州", "北海", "玉林"] },
  { province: "海南", cities: ["海口", "三亚", "儋州", "琼海"] },
  { province: "四川", cities: ["成都", "绵阳", "德阳", "南充", "宜宾", "乐山"] },
  { province: "贵州", cities: ["贵阳", "遵义", "六盘水", "毕节"] },
  { province: "云南", cities: ["昆明", "曲靖", "大理", "红河", "玉溪", "丽江"] },
  { province: "西藏", cities: ["拉萨", "日喀则", "林芝"] },
  { province: "陕西", cities: ["西安", "咸阳", "宝鸡", "榆林", "渭南"] },
  { province: "甘肃", cities: ["兰州", "天水", "酒泉", "庆阳"] },
  { province: "青海", cities: ["西宁", "海东", "格尔木"] },
  { province: "宁夏", cities: ["银川", "石嘴山", "吴忠", "中卫"] },
  { province: "新疆", cities: ["乌鲁木齐", "喀什", "伊犁", "昌吉", "库尔勒"] },
  { province: "香港", cities: ["香港"] },
  { province: "澳门", cities: ["澳门"] },
  { province: "台湾", cities: ["台北", "台中", "高雄", "台南"] },
  { province: "海外/其他", cities: ["其他地区"] },
] as const;

export type RegionOption = (typeof REGION_OPTIONS)[number];
